// Source of truth: api/src/constants/userConstants.ts
// If you update this list, update all three packages

const List<String> majorList = [
    "Accounting",
    "Actuarial Science",
    "Advertising/Public Relations",
    "Aerospace Engineering",
    "Anthropology",
    "Architecture",
    "Art",
    "Biology",
    "Biomedical Sciences",
    "Biotechnology",
    "Business Economics",
    "Career and Technical Education",
    "Chemistry",
    "Civil Engineering",
    "Communication",
    "Communication and Conflict",
    "Communication Sciences and Disorders",
    "Computer Engineering",
    "Computer Science",
    "Construction Engineering",
    "Criminal Justice",
    "Data Science",
    "Digital Media",
    "Early Childhood Development and Education",
    "Economics",
    "Electrical Engineering",
    "Elementary Education",
    "Emergency Management",
    "Emerging Media",
    "English",
    "Entertainment Management",
    "Environmental Engineering",
    "Environmental Science",
    "Environmental Studies",
    "Event Management",
    "Exceptional Student Education",
    "Film",
    "Finance",
    "Forensic Science",
    "French and Francophone Studies",
    "General Health Studies",
    "Health Informatics",
    "Health Informatics and Information Management",
    "Health Sciences",
    "History",
    "Hospitality Management",
    "Industrial Engineering",
    "Information Technology",
    "Integrative General Studies",
    "Interdisciplinary Studies",
    "International and Global Studies",
    "Journalism",
    "Latin American, Caribbean and Latinx Studies",
    "Legal Studies",
    "Lifestyle Community Management",
    "Lodging and Restaurant Management",
    "Management",
    "Marketing",
    "Materials Science and Engineering",
    "Mathematics",
    "Mechanical Engineering",
    "Medical Laboratory Sciences",
    "Molecular and Cellular Biology",
    "Molecular Microbiology",
    "Music",
    "Nonprofit Management",
    "Nursing",
    "Philosophy",
    "Photonic Science and Engineering",
    "Physics",
    "Political Science",
    "Psychology",
    "Public Administration",
    "Real Estate",
    "Religion and Cultural Studies",
    "Risk Management and Insurance",
    "Secondary Education",
    "Social Sciences",
    "Social Work",
    "Sociology",
    "Spanish",
    "Statistics",
    "Theatre",
    "Theatre Studies",
    "Writing and Rhetoric"
];

const List<String> genderOptions = ["Male", "Female", "Non-Binary", "Other", "Unspecified"];

const List<String> classYearOptions = ["Freshman", "Sophomore", "Junior", "Senior", "Graduate", "Other"];